// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Problema2_7_412201_IngIndirecta.Models;

public partial class Servicios
{
    public int IdServicio { get; set; }

    public string Nombre { get; set; }

    public int Costo { get; set; }

    public bool? EnPromocion { get; set; }

    public virtual ICollection<DetalleTurnos> DetalleTurnos { get; set; } = new List<DetalleTurnos>();
}