// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Problema2_7_412201_IngIndirecta.Models;

public partial class DetalleTurnos
{
    public int IdDetalle { get; set; }

    public int TurnoIdTurno { get; set; }

    public int ServicioIdServicio { get; set; }

    public string Observaciones { get; set; }

    public virtual Servicios ServicioIdServicioNavigation { get; set; }

    public virtual Turnos TurnoIdTurnoNavigation { get; set; }
}