// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Problema2_7_412201_IngIndirecta.Models;

public partial class Turnos
{
    public int IdTurno { get; set; }

    public DateTime Fecha { get; set; }

    public string Cliente { get; set; }

    public virtual ICollection<DetalleTurnos> DetalleTurnos { get; set; } = new List<DetalleTurnos>();
}